mymultifields/appmulti/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ForwardListView, ForwardUpdateView

app_name = 'appmulti'

urlpatterns = [
    path('', ForwardListView.as_view(), name='forward_list'),
    path('forward/<int:pk>/edit', ForwardUpdateView.as_view(), name='edit_forward'),
]

mymultifields/files_check/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import MainPage, model_form_upload, take_files_two

app_name = 'file_check'

urlpatterns = [
    path('main/', MainPage.as_view(), name='index'),
    path('upload/', model_form_upload, name='upload'),
    path('check/<int:pk>/', take_files_two, name='check'),
]

mymultifields/mymultifields/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appmulti.urls', namespace='multi')),
    path('files/', include('files_check.urls', namespace='files_check')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymultifields/appmulti/models.py
from django.db import models


class Forward(models.Model):
    forward_class = models.CharField(max_length=100)


class Option(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    forward = models.ForeignKey(Forward, on_delete=models.CASCADE, related_name='options')
    type_of_field = models.CharField(max_length=10,
                                     choices=(('general', 'Тип данных не известен'),
                                              ('int', 'Число целое'),
                                              ('float', 'Число с плавающей точкой'),
                                              ('dict', 'Словарь')),
                                     default='general')

mymultifields/files_check/models.py
from django.db import models


class DocCheck(models.Model):
    title = models.CharField(max_length=25)
    file_mssp = models.FileField(upload_to='documents/mssp/')
    file_quotes = models.FileField(upload_to='documents/quotes/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class CheckerFiles(models.Model):
    title = models.CharField(max_length=25)
    dock_check = models.ForeignKey(DocCheck,
                                   on_delete=models.CASCADE,
                                   related_name='check_files')
    result = models.CharField(max_length=25)
    checked_at = models.DateTimeField(auto_now_add=True)

mymultifields/files_check/forms.py
from django import forms
from .models import DocCheck


class DocCheckForm(forms.ModelForm):
    class Meta:
        model = DocCheck
        fields = ['title', 'file_mssp', 'file_quotes']

mymultifields/appmulti/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Forward, Option
from django.views.generic.edit import UpdateView
from django.forms import modelform_factory, inlineformset_factory


class ForwardListView(ListView):
    model = Forward
    template_name = 'appmulti/forward_list.html'
    context_object_name = 'forwards'


class ForwardUpdateView(UpdateView):
    model = Forward
    fields = ['forward_class']
    template_name = 'appmulti/edit_forward.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OptionFormSet = inlineformset_factory(Forward, Option, fields=('name', 'description', 'type_of_field'), extra=1)
        if self.request.POST:
            data['option_formset'] = OptionFormSet(self.request.POST, instance=self.object)
        else:
            data['option_formset'] = OptionFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        option_formset = context['option_formset']
        if option_formset.is_valid():
            self.object = form.save()
            option_formset.instance = self.object
            option_formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

mymultifields/files_check/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DocCheckForm
from django.views.generic.base import TemplateView
from .models import DocCheck, CheckerFiles
from appmulti.models import Forward, Option

def model_form_upload(request):
    if request.method == 'POST':
        form = DocCheckForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index.html')
    else:
        form = DocCheckForm()
    context = {
        'form': form
    }
    return render(request, 'files_check/upload.html', context=context)


class MainPage(TemplateView):
    template_name = 'files_check/index.html'


def take_files_two(request, pk):
    files_obj = get_object_or_404(DocCheck, pk=pk)
    if files_obj.file_mssp:
        result = 'Сверка завершена'
    else:
        result = 'Error - no file'
    checking = CheckerFiles(title=files_obj.title + ' check', dock_check=files_obj, result=result)
    checking.save()
    forwards = Forward.objects.all()
    context = {
        'checking': checking,
        'forwards': forwards,
    }
    return render(request, 'files_check/check_info.html', context=context)

mymultifields/appmulti/templates/appmulti/check_info.html
{% extends 'base.html' %}
{% block title %}
    Страница проверки
{% endblock %}
{% block content %}
    <h1>Проверка</h1>

{% endblock %}

mymultifields/appmulti/templates/appmulti/edit_forward.html
{% extends 'base.html' %}
{% block title %}
    Редактировать форвард
{% endblock %}

{% block content %}
    <h1>Редактирование форварда</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ option_formset.management_form }}
            {% for form in option_formset %}
                {{ form.as_p }}
            {% endfor %}
        <input type="submit" value="Обновить пост">
    </form>
{% endblock %}

mymultifields/appmulti/templates/appmulti/forward_list.html
{% extends 'base.html' %}

{% block title %}
    Список форвардов
{% endblock %}

{% block content %}
    {% for forward in forwards %}
        <div>
        Название феникса: {{ forward.forward_class }}
            <br>
            <br>
        {% for option in forward.options.all %}
            <li>
                <strong>Поле:</strong> {{ option.name }}<br>
                <strong>Откуда брать из дилса:</strong> {{ option.description }}<br>
                <strong>Ожидаю получить тип данных:</strong> {{ option.type_of_field }}
            </li>

        {% endfor %}
        </div>
        <div>
        <hr>
        </div>
    {% endfor %}
    
{% endblock %}

mymultifields/appmulti/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}

      {% endblock %}
    </title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

mymultifields/files_check/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}

      {% endblock %}
    </title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

mymultifields/files_check/templates/files_check/check_info.html
{% extends 'base.html' %}
{% block title %}
    Страница проверки
{% endblock %}
{% block content %}
    <h1>Проверка</h1>
    <p>Заголовок = {{ checking.title }}</p>
    <p>Кого проверяли = {{ checking.dock_check }}</p>
    <p>Результат проверки = {{ checking.result }}</p>
    <div>
        {% for forward in forwards %}
            <p>Форвард = {{ forward.forward_class }}</p>
            <p>{% for option in forward.options.all %}
                <p>Имя опции форварда = {{ option.name }}</p>
                <p>Описание опции форварда = {{ option.description }}</p>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}

mymultifields/files_check/templates/files_check/index.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <h1>Главная</h1>
{% endblock %}

mymultifields/files_check/templates/files_check/upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'files_check:index' %}">Return to home</a></p>
{% endblock %}